import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import CodeEditorSVG from '../../components/CodeEditor/CodeEditor'
import AboutMeButton from '../../components/AboutMeButton/AboutMeButton'
import MyProjectsButton from '../../components/MyProjectsButton/MyProjectsButton'
import styles from '../styles/home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Elbert</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.hero}>

        <CodeEditorSVG id={styles.heroCodeEditor} text='print("Hello World!")' animate={true}/>

        <div className={styles.heroTextWrapper}>

          <div className={styles.heroText}>

            <div className={styles.headerText}>
              <div>Hello World!</div>
              <div>I'm Elbert.</div>
            </div>

            <div className={styles.subheaderText}>
                I’m a bioinformatics student with a soft spot for frontend development.
            </div>
            
            <div className={styles.buttonRow}>
              <AboutMeButton id={styles.aboutMeButton}/>
              <MyProjectsButton id={styles.myProjectsButton}/>
            </div>
          </div>

        </div>

      </div>
      
    </>
  )
}
