import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import CodeEditorSVG from "../../components/CodeEditor/CodeEditor";
import AboutMeButton from "../../components/AboutMeButton/AboutMeButton";
import MyProjectsButton from "../../components/MyProjectsButton/MyProjectsButton";
import RedHeartIcon from "../../icons/RedHeartIcon";
import homeStyle from "../styles/home.module.scss";
import projectsStyle from '../styles/projects.module.scss'
import Navbar from "../../layouts/Navbar";
import ScrollDirection from "../../layouts/ScrollDirection";
import ProjectCard from "../../components/ProjectCard/ProjectCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Elbert</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar>
        <ScrollDirection pageNames={['home', 'projects', 'about']} pageColors={['#F1FFFB','#CAE5FF','#a4f4d9']}>
          <div className={homeStyle.hero}>
            <CodeEditorSVG
              id={homeStyle.heroCodeEditor}
              text='print("Hello World!")'
              animate={true}
            />

            <div className={homeStyle.heroTextWrapper}>
              <div className={homeStyle.heroText}>
                <div className={homeStyle.headerText}>
                  <div>Hello World!</div>
                  <div>I&apos;m Elbert.</div>
                </div>

                <div className={homeStyle.subheaderText}>
                  I’m a bioinformatics student with a soft spot for frontend
                  development.
                  <RedHeartIcon
                    fontSize='clamp(30px,2vw,40px)'
                    display='inline-block'
                  />
                </div>

                <div className={homeStyle.buttonRow}>
                  <MyProjectsButton id={homeStyle.myProjectsButton} />
                  <AboutMeButton id={homeStyle.aboutMeButton} />
                </div>
              </div>
            </div>
          </div>
          <div className={projectsStyle.projects}>
            <div className={projectsStyle.projectCardsWrapper}>
              <ProjectCard />
              <ProjectCard />
              <ProjectCard />
            </div>
          </div>
          <div className={homeStyle.about}></div>
        </ScrollDirection>
      </Navbar>
    </>
  );
}
