import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import CodeEditorSVG from '../../components/CodeEditor/CodeEditor'
import AboutMeButton from '../../components/AboutMeButton/AboutMeButton'
import MyProjectsButton from '../../components/MyProjectsButton/MyProjectsButton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Elbert</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='hero'>

        <CodeEditorSVG id='hero-code-editor'/>

        <div className='hero-text-wrapper'>

          <div className='hero-text'>

            <div className='header-text'>
              <div>Hello World!</div>
              <div>I'm Elbert.</div>
            </div>

            <div className='subheader-text'>
                I’m a bioinformatics student with a soft spot for frontend development.
            </div>
            
            <div className='button-row'>
              <AboutMeButton id='about-me-button'/>
              <MyProjectsButton id='my-projects-button'/>
            </div>
          </div>

        </div>

      </div>
      
    </>
  )
}
